alias l="ls"
alias v.="vim ."
alias vi="vim"

# ruby
alias b="bundle"
alias mm="middleman"
alias mmb="middleman build"
alias mms="middleman server --host localhost"
alias rcs="rails console --sandbox"
alias rgc="rvm gemset create"
alias rgl="rvm gemset list"
alias rgu="rvm gemset use"
alias rsbl="rails server --bind localhost"

# git
alias gaa="git add --all"
alias gap="git add --patch"
alias gb="git branch"
alias gca="git commit --amend"
alias gcaa="git commit --amend -CHEAD"
alias gcam="git commit --amend --message"
alias gcl="git clone"
alias gcm="git commit --message"
alias gco="git checkout"
alias gcom="git checkout master"
alias gf="git fetch"
alias gfr="git pull --rebase"
alias gg="git checkout -"
alias gl="git lola"
alias gp="git push"
alias gpf="git push --force"
alias gra="git rebase --abort"
alias grc="git rebase --continue"
alias gri="git rebase --interactive"
alias gs="git stash"
alias gsa="git stash apply"

alias zsrc="exec zsh -l"
